config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home_page#index"
  # Defines the root path route ("/")
  # root "posts#index"
  # 
  resources :posts, only: [:index, :create, :destroy, :update, :edit] do
    resources :comments, only: [:create, :destroy, :update, :edit]
  end
  
  resources :users do
    member do
      post 'follow'
      post 'unfollow'
    end
  end
  
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include ActionView::Helpers::SanitizeHelper
  before_save :format_text
  belongs_to :post
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true

  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy, inverse_of: :parent

  validates :content, presence: true, length: { minimum: 1, maximum: 70 }

  def level
    parent_id.nil? ? 0 : parent.level + 1
  end

  private

  def format_text
    self.content = content.gsub(/<.*?>/, '').gsub(/(.{1,20})/, "\\1\n")
  end
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :user, class_name: 'User'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include ActionView::Helpers::SanitizeHelper
  before_save :format_text
  belongs_to :user

  has_many :comments, dependent: :destroy
  validates :content, presence: { message: 'Публикация не может быть пустой!' },
                      length: { minimum: 5, maximum: 90,
                                too_short: 'Публикация должна быть не менее 5 символов!',
                                too_long: 'Публикация должна быть не более 90 символов!' }

  private

  def format_text
    self.content = content.gsub(/<.*?>/, '').gsub(/(.{1,20})/, "\\1\n")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  has_many :follower_relationships, class_name: 'Follow', dependent: :destroy, inverse_of: :user
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :following_relationships, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy,
                                     inverse_of: :follower
  has_many :following, through: :following_relationships, source: :user
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def not_me
    User.where.not(id:)
  end

  def following_posts
    following_ids = following.pluck(:id)
    Post.where(user_id: following_ids)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordInvalid, with: :error_handling
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  private

  def error_handling(exception)
    flash[:notice] = exception.record.errors.messages[:content].join(', ')
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[edit update destroy]

  def create
    @comment = @post.comments.create!(comment_params.merge(user: current_user))
    redirect_back(fallback_location: root_path)
  end

  def edit; end

  def destroy
    # if @comment.user == current_user
    #  @comment.soft_delete
    #  flash[:notice] = 'Комментарий успешно удален.'
    # end
    # redirect_back(fallback_location: root_path)

    @comment = Comment.find(params[:id])

    if @comment.user == current_user
      delete_sub_comments(@comment)
      @comment.destroy
      flash[:notice] = 'Комментарий успешно удален.'
    end

    redirect_back(fallback_location: root_path)
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Комментарий обновлен.'
      redirect_to posts_path
    else
      redirect_to edit_post_comment_path(@comment), notice: 'Комментарий не удалось обновить.'
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end

  def delete_sub_comments(comment)
    comment.replies.each do |child|
      delete_sub_comments(child)
      child.destroy!
    end
  end
end

app/controllers/home_page_controller.rb
# frozen_string_literal: true

class HomePageController < ApplicationController
  before_action :authenticate_user!
  before_action :set_users

  def index
    @my_posts = current_user.posts.order(created_at: :desc)
    @following_posts = current_user.following_posts
  end

  def set_users
    @users = User.where.not(id: current_user.id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @post = current_user.posts.create!(post_params)
    redirect_to root_path, notice: 'Публикация создана!'
  end

  def edit
    @post = current_user.posts.find(params[:id])
    @initial_content = @post.content
  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.update!(post_params)
    redirect_to root_path, notice: 'Публикация обновлена!'
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to root_path, notice: 'Публикация удалена!'
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def follow
    current_user.following_relationships.create(user_id: params[:id])
    redirect_to user_path(params[:id]), notice: 'Вы подписались!'
  end

  def unfollow
    current_user.following_relationships.find_by(user_id: params[:id]).destroy
    redirect_to user_path(params[:id]), notice: 'Вы отписались!'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_page_helper.rb
# frozen_string_literal: true

module HomePageHelper
end

app/views/comments/edit.html.erb
<h2>Редактировать комментарий</h2>
<%= flash[:notice] %>
</br>

<%= form_with(model: [@comment.post, @comment], local: true) do |form| %>
  <div>
    <%= form.text_area :content, id: "comment_content", placeholder: "Редактировать комментарий..." %>
  </div>
  <%= form.submit "Сохранить изменения", class: "update-comment", disabled: true %>
<% end %>

<%= link_to 'Назад', root_path %>

<script>
  var initialContent = document.querySelector('#comment_content').value
  document.querySelector('#comment_content').addEventListener('input', () => {
    var content = document.querySelector('#comment_content').value
    document.querySelector('.update-comment').disabled = false
    if (content === initialContent) {
      document.querySelector('.update-comment').disabled = true
    }
  })
</script>

app/views/home_page/index.html.erb
<% if user_signed_in? %>
  <%= button_to 'Выйти', destroy_user_session_path, class: 'btn btn-primary sign_out', :method => :delete %>

  <%= button_to 'Мой профиль', user_path(current_user), class: 'btn btn-primary registration', :method => :get  %>

  <div class="content-container">
    <%= form_with(model: Post.new, url: posts_path, local: true) do |form| %>
      <h4> Здравствуйте, <%= current_user.email.gsub(/<.*?>/,'').gsub(/(.{1,20})/, "\\1\n") %> </h4>
      <div>
        <%= form.text_area :content, placeholder: "Что у вас нового?" %>
      </div>
      <%= form.submit "Опубликовать" %>  <br/> <br/>
      <%= flash[:notice] %>
    <% end %>
    <h2>Ваши публикации</h2>
    <% if @my_posts.present? %>
      <p>Всего ваших публикаций: <%= @my_posts.count %></p>
      <% @my_posts.each do |post| %>
        <p>
          <br/> Вы: <%=  simple_format(post.content) %>
          <div style="display: inline-flex; gap: 10px;">
            <%= post.created_at.strftime("%-d.%m.%Y, %H:%M") %>  
            <%= button_to 'Редактировать', edit_post_path(post), method: :get, class: 'btn btn-primary' %>
            <%= button_to 'Удалить', post_path(post), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger' %>
          </div>
        </p>
      <% end %>
    <% else %>
      <p>У вас пока нет публикаций.</p>
    <% end %>
  </div>  

  <div class="users-section">
  <h2>Пользователи</h2>
    <ul>
      <% if @users.present? %>
        <% @users.each do |user| %>
          <% unless user == current_user %> 
            <li>
              <%= link_to user.email, user_path(user) %>
            </li>
          <% end %>
        <% end %>
      <% else %>
        <p>Нет других пользователей для отображения.</p>
      <% end %>
    </ul>
  </div>

  <div class="following-section">
    <h1>Лента</h1>
    <% if @following_posts.present? %>
      <% @following_posts.each do |post| %>
        <p>
          <%= post.user.email %>: <%= post.created_at.strftime("%-d.%m.%Y, %H:%M") %><br> 
          Пост:  <%= post.content %>
          <%= form_with(model: [post, Comment.new], url: post_comments_path(post), local: true) do |form| %>
            <div style="display: flex; align-items: center;">
              <%= form.text_area :content, placeholder: "Комментарий..." %>
              <%= form.hidden_field :parent_id %>
              <%= form.submit "Добавить комментарий", style: "margin-left: 10px;" %>
            </div>
          <% end %>
          <%= render partial: 'posts/comment', collection: post.comments.where(parent_id: nil), as: :comment %>
        </p>
      <% end %>
    <% else %>
      <p>Пока нет публикаций от подписчиков.</p>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<% margin_left = 10 + comment.level * 30 %>

<div style="margin-left: <%= margin_left %>px;">
  <div style="display: inline-flex; align-items: center; gap: 10px; margin-top: 10px; max-width: 100px;">
    Комментарий:  <%= comment.content.html_safe %><br>  
    <%= comment.created_at.strftime('%-d %m %Y, %H:%M') %> <%= comment.user.email %>
    <% if comment.user == current_user %>
      <%= button_to 'Изменить', edit_post_comment_path(comment.post, comment), method: :get, class: 'btn btn-warning' %>
      <%= button_to 'Удалить', post_comment_path(comment.post, comment), method: :delete,  
          data: { confirm: 'Вы уверены, что хотите удалить этот комментарий и все его ответы?' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

<% unless comment.user == current_user %> 
  <%= form_with(model: [comment.post, Comment.new], url: post_comments_path(comment.post), local: true) do |form| %>
    <div style="margin-left: <%= margin_left + 20 %>px; display: flex; align-items: center;">
      <%= form.text_area(:content, placeholder: "Ответ на комментарий...", style: "margin-right: 10px;") %>
      <%= form.hidden_field(:parent_id, value: comment.id) %>
      <%= form.submit("Ответить", style: "margin-top: 0;") %> 
    </div>
  <% end %>
<% end %>

<hr style="margin-left: <%= margin_left %>px; margin-top: 10px; margin-bottom: 10px;">

<%= render partial: 'posts/comment', collection: comment.replies, as: :comment if comment.replies.any? %>

app/views/posts/edit.html.erb
<h1>Редактировать публикацию</h1>
<%= flash[:notice] %>
</br>

<%= form_with(model: @post, local: true) do |form| %>
  <div>
    <%= form.text_area :content, placeholder: "Редактировать публикацию..." %>
  </div>
  <%= form.submit "Обновить", class: "update-post", disabled: true %>
<% end %>

<%= link_to 'Назад', root_path %>
<script>
  var initialContent = document.querySelector('#post_content').value
  document.querySelector('#post_content').addEventListener('input', () => {
  var content = document.querySelector('#post_content').value
  document.querySelector('.update-post').disabled = false
  if (content === initialContent) {
    document.querySelector('.update-post').disabled = true
  }
})
</script>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
 <%= flash[:notice] %>

<% if current_user != @user %>
  <% if current_user.following.include?(@user) %>
    <%= button_to 'Отписаться', unfollow_user_path(@user), method: :post %>
  <% else %>
    <%= button_to 'Подписаться', follow_user_path(@user), method: :post %>
  <% end %>
<% end %>

<h2>Публикации</h2>
<% if @posts.present? %>
  <% @posts.each do |post| %>
    <p>
      <%= post.user.email %>: <%= post.created_at.strftime("%-d.%m.%Y, %H:%M")%> 
      </br>Пост: <%= post.content %>
    </p>
  <% end %>
<% else %>
  <p>У этого пользователя пока нет публикаций.</p>
<% end %>

<%= link_to 'Назад', root_path %>